initial fix for generating code for export.
need to remove console logs still.

but saving before rectifying the error here:
TypeError: Cannot read properties of undefined (reading 'mode') at getAuthHeaders (http://localhost:3000/static/js/index.js:83116:17) at CodeView (http://localhost:3000/index.38d30042ecc42668.hot-update.js:107:86) at react-stack-bottom-frame (http://localhost:3000/static/js/lib-react.js:12201:18) at renderWithHooks (http://localhost:3000/static/js/lib-react.js:3518:20) at updateFunctionComponent (http://localhost:3000/static/js/lib-react.js:4787:17) at beginWork (http://localhost:3000/static/js/lib-react.js:5405:16) at runWithFiberInDEV (http://localhost:3000/static/js/lib-react.js:746:14) at performUnitOfWork (http://localhost:3000/static/js/lib-react.js:7990:93) at workLoopSync (http://localhost:3000/static/js/lib-react.js:7884:38) at renderRootSync (http://localhost:3000/static/js/lib-react.js:7868:7)
message
:
"Cannot read properties of undefined (reading 'mode')"
stack
:
"TypeError: Cannot read properties of undefined (reading 'mode')\n at getAuthHeaders (http://localhost:3000/static/js/index.js:83116:17)\n at CodeView (http://localhost:3000/index.38d30042ecc42668.hot-update.js:107:86)\n at react-stack-bottom-frame (http://localhost:3000/static/js/lib-react.js:12201:18)\n at renderWithHooks (http://localhost:3000/static/js/lib-react.js:3518:20)\n at updateFunctionComponent (http://localhost:3000/static/js/lib-react.js:4787:17)\n at beginWork (http://localhost:3000/static/js/lib-react.js:5405:16)\n at runWithFiberInDEV (http://localhost:3000/static/js/lib-react.js:746:14)\n at performUnitOfWork (http://localhost:3000/static/js/lib-react.js:7990:93)\n at workLoopSync (http://localhost:3000/static/js/lib-react.js:7884:38)\n at renderRootSync (http://localhost:3000/static/js/lib-react.js:7868:7)"